-- QR Validation System for PetoClub
-- Allows businesses to validate coupons via QR scan or 15-min alphanumeric codes

-- QR Codes table: one QR per business
CREATE TABLE public.business_qr (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE UNIQUE NOT NULL,
  qr_token UUID NOT NULL DEFAULT uuid_generate_v4(),
  qr_image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Validation codes: generated by users when redeeming coupons
-- These are 8-character alphanumeric codes valid for 15 minutes
CREATE TABLE public.validation_codes (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  code TEXT NOT NULL, -- 8 char alphanumeric
  business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  discount_id UUID REFERENCES public.discounts(id) ON DELETE CASCADE,
  coupon_code TEXT NOT NULL, -- the discount coupon code being redeemed
  expires_at TIMESTAMPTZ NOT NULL, -- 15 minutes from creation
  is_used BOOLEAN DEFAULT FALSE,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for quick code lookup
CREATE INDEX idx_validation_codes_code ON public.validation_codes(code);
CREATE INDEX idx_validation_codes_expires ON public.validation_codes(expires_at);

-- RLS Policies
ALTER TABLE public.business_qr ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.validation_codes ENABLE ROW LEVEL SECURITY;

-- Anyone can read business QR (for validation)
CREATE POLICY "QR codes are viewable by everyone"
  ON public.business_qr FOR SELECT USING (true);

-- Only business owner can manage their QR
CREATE POLICY "Business owners can manage their QR"
  ON public.business_qr FOR ALL USING (
    EXISTS (SELECT 1 FROM public.businesses WHERE id = business_id AND owner_id = auth.uid())
  );

-- Anyone can create validation codes (user with coupon)
CREATE POLICY "Authenticated users can create validation codes"
  ON public.validation_codes FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Business owners can view their validation codes
CREATE POLICY "Business owners can view their validation codes"
  ON public.validation_codes FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.businesses WHERE id = business_id AND owner_id = auth.uid())
  );

-- Business owners can mark codes as used
CREATE POLICY "Business owners can update validation codes"
  ON public.validation_codes FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.businesses WHERE id = business_id AND owner_id = auth.uid())
  );

-- Function to generate random 8-char alphanumeric code
CREATE OR REPLACE FUNCTION public.generate_validation_code()
RETURNS TEXT AS $$
DECLARE
  chars TEXT := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; -- Removed confusing chars (0,O,1,I)
  result TEXT := '';
  i INTEGER := 0;
BEGIN
  FOR i IN 1..8 LOOP
    result := result || substr(chars, floor(random() * length(chars) + 1)::integer, 1);
  END LOOP;
  RETURN result;
END;
$$ LANGUAGE plpgsql;

-- Function to create validation code (15 min expiry)
CREATE OR REPLACE FUNCTION public.create_validation_code(
  p_business_id UUID,
  p_user_id UUID,
  p_discount_id UUID,
  p_coupon_code TEXT
)
RETURNS TABLE(code TEXT, expires_at TIMESTAMPTZ) AS $$
DECLARE
  v_code TEXT;
  v_expires TIMESTAMPTZ;
BEGIN
  v_code := generate_validation_code();
  v_expires := NOW() + INTERVAL '15 minutes';
  
  INSERT INTO public.validation_codes (code, business_id, user_id, discount_id, coupon_code, expires_at)
  VALUES (v_code, p_business_id, p_user_id, p_discount_id, p_coupon_code, v_expires)
  RETURNING code, expires_at INTO code, expires_at;
  
  RETURN NEXT;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to validate (use) a code
CREATE OR REPLACE FUNCTION public.use_validation_code(p_code TEXT)
RETURNS BOOLEAN AS $$
DECLARE
  v_record RECORD;
BEGIN
  -- Find the code
  SELECT * INTO v_record
  FROM public.validation_codes
  WHERE code = p_code AND is_used = FALSE AND expires_at > NOW();
  
  IF v_record IS NULL THEN
    RETURN FALSE;
  END IF;
  
  -- Mark as used
  UPDATE public.validation_codes
  SET is_used = TRUE, used_at = NOW()
  WHERE id = v_record.id;
  
  RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Auto-create QR when business is created
CREATE OR REPLACE FUNCTION public.create_business_qr()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.business_qr (business_id)
  VALUES (NEW.id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_business_created
  AFTER INSERT ON public.businesses
  FOR EACH ROW EXECUTE FUNCTION public.create_business_qr();

-- Add business_id column to discounts for easier lookup
ALTER TABLE public.discounts
ADD COLUMN IF NOT EXISTS business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE;

-- Backfill business_id from existing discount records
UPDATE public.discounts d
SET business_id = b.id
FROM public.businesses b
WHERE b.owner_id IN (
  SELECT owner_id FROM public.businesses
);

-- Make business_id NOT NULL for discounts (each discount belongs to a business)
ALTER TABLE public.discounts
ALTER COLUMN business_id SET NOT NULL;
